#ifndef CONTROLMI_PMIK_MIDI_CONSTS_HPP
#define CONTROLMI_PMIK_MIDI_CONSTS_HPP

#define DATA_CHANNEL 0
#define NOTE_CHANNEL 1

#define CC_SLIDER_CH1 0
#define CC_SLIDER_CH2 1
#define CC_SLIDER_CH3 2
#define CC_SLIDER_CH4 3
#define CC_SLIDER_CH5 4
#define CC_SLIDER_CH6 5
#define CC_SLIDER_MAIN 6

#define CC_MODULATION 1
#define CC_PAN 8

#define CC_NAV_LEFT  40
#define CC_NAV_RIGHT 41
#define CC_PLAY 33

#define CC_VALUE_OFF 0
#define CC_VALUE_ON 127

#endif //CONTROLMI_PMIK_MIDI_CONSTS_HPP
